### ISSUE TITLE
Spindle Set-Up on MKS DLC 32 V2.1

### ISSUE THREAD

**Issue by Christo-Fourie** [dJOS1475/grblHAL_Backup#1]
Good day

I came across your grblHAL_Backup for the MKS DLC32 after about a week of trying to get grblHAL on my board. Needless to say, the firmware works. So a big thank you for that.

I now ran into a problem with the spindle control.

My physical setup is as follows: (Picture below)
![IMG_20240825_120431](https://github.com/user-attachments/assets/fdfca4a2-15d4-4a20-b777-7b0b926bf9e7)

I have a 400W DC Spindle, powered by a 400W Power Supply. Speed is controlled with a DC Motor Control Box and a POT.
I also have an SRD-12VDC-SL-C Relay module used to "Power On" the 400W Power Supply.

The relay is connected to the Spindle + and - on the MKS DLC32 and GRN.

The idea is that a 5v signal from the controller will trigger the relay which switches the Power Supply on. The speed is controlled manually with the POT and DC Motor Control Box.

My problem is that the "Spindle -" pin has 2.6V on it the whole time. This is enough to trigger the relay. So when I power up the board, the spindle switches on.

I understand you have a Makita Router on your machine, but I would appreciate any input or ideas on this setup.

Thank you
Christo

**Comment by dJOS1475** [comment]
Howdy, Im glad it was helpful - my suggestion is to configure the spindle like this:

Set spindle speed range to the max RPM of your spindle:

; 30 - Maximum spindle speed
$30=12000.000
; 31 - Minimum spindle speed
$31=12000.000

and this should enable it to run as basically on/off only:

; 33 - Spindle PWM frequency
$33=1000
; 34 - Spindle PWM off value
$34=0.0
; 35 - Spindle PWM min value
$35=100.0
; 36 - Spindle PWM max value
$36=100.0

I hope this helps, 
Cheers Derek

**Comment by Christo-Fourie** [comment]
Hi Derek

Thanks for the reply.

I have applied those settings and it's still not working. Screenshot of settings below:
![Screenshot 2024-08-25 154602](https://github.com/user-attachments/assets/440584ae-fa58-4c35-9320-ca2f5ff7d88d)

I also took some measurements and found the following:

Spindle + has 12vdc on it (Board supply voltage is 12vdc)
Spindle - (this is the GPIO32 pin on the MKS DLC32) has 10.85vdc when measured against GND - Spindle Off
Spindle - has 10.60vdc when measured against GND - Spindle On

I use the Spindle Plugin on iOSender to test the above:
![Screenshot 2024-08-25 155158](https://github.com/user-attachments/assets/a70511b2-c8b7-482a-b3fa-64cba16fb54c)

So the voltage on the Spindle - pin, which is from what I understand the PWM signal pin, only moves by 0.25vdc when switching the spindle on and off.

I am stuck and having spent hours on every CNC-related forum I could find I am nowhere closer to understanding this.

Thanks

**Comment by dJOS1475** [comment]
Hmmm, I think you might need to compile your firmware with the on/off option instead of PWM.

![SCR-20240826-hlfi](https://github.com/user-attachments/assets/381cd65d-6b3b-48af-9abe-432bb6987d27)

http://svn.io-engineering.com:8080/?driver=ESP32&board=MKS%20DLC32%202.0

**Comment by Christo-Fourie** [comment]
That makes sense.

I will do that tonight and see what happens.

Thank you for the help. It is much appreciated.

**Comment by Christo-Fourie** [comment]
Hi

Setting the spindle to on/off made no change.

I posted a question here (https://github.com/grblHAL/core/discussions/203?sort=old#discussioncomment-10454788) as well to see if I can get a fix from the grblHAL community.

Thanks

**Comment by dJOS1475** [comment]
Ah that’s a shame, hopefully they can help you there.

**Comment by Christo-Fourie** [comment]
My issue has been resolved. The MKS DLC32 Map from grblHAL referenced the GPIO27 pin instead of the GPIO32.

Terjeio from grblHAL updated the map file and the firmware downloaded from the web builder works like a charm now.

Thank you for the idea to set the spindle to on/off. Without that, I wouldn't have gotten to the fix.

Thanks

**Comment by dJOS1475** [comment]
Outstanding! I wonder when the map got changed to cause this issue.
